openapi: '3.0.3'
info:
  title: 'Energy Tracker API'
  description: 'API for Energy Tracker'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: '0.0.1'

servers:
  - url: http://localhost:8080

paths:
  /meter-readings:
    get:
      summary: 'Gets a list of meter readings'
      operationId: 'getMeterReadings'
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeterReadingCollection'
    post:
      summary: 'Creates a meter reading'
      operationId: 'createMeterReading'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeterReading'
        required: true
      responses:
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        201:
          description: 'Created'
          headers:
            Location:
              description: The location of the created resource
              schema:
                type: string
components:
  schemas:
    Links:
      type: object
      required:
        - self
      properties:
        self:
          $ref: '#/components/schemas/Link'
    #      additionalProperties:
    #        $ref: '#/components/schemas/Link'
    Link:
      type: object
      required:
        - href
      properties:
        href:
          type: string
        templated:
          type: boolean
        type:
          type: string
        name:
          type: string
        title:
          type: string
    Problem:
      type: object
      description: Object describing a problem using RFC7807
      properties:
        title:
          type: 'string'
        status:
          type: 'int'
    MeterReadingCollection:
      type: 'object'
      properties:
        _embedded:
          type: 'object'
          properties:
            meterReadings:
              type: 'array'
              items:
                $ref: '#/components/schemas/MeterReading'
    MeterReading:
      type: object
      required:
        - electricityNormal
        - electricityLow
        - gas
        - water
      properties:
        id:
          type: string
          format: uuid
        electricityNormal:
          type: number
          format: double
        electricityLow:
          type: number
          format: double
        gas:
          type: number
          format: double
        water:
          type: number
          format: double
        timestamp:
          type: string
          format: date-time
