spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energy-tracker
    username: energy-tracker
    password: energy-tracker
    driver-class-name: org.postgresql.Driver
#  jpa.hibernate.ddl-auto: create